<#
.SYNOPSIS
    Generates an NSIS installer for the MSMQ Manager application.

.DESCRIPTION
    This script creates an NSIS installer script and builds the installer for the
    MSMQ Manager application. The installer allows users to choose installation
    path and automatically registers the Windows service.

.PARAMETER OutputPath
    The directory where the installer will be created. Default: .\installer

.PARAMETER DistPath
    Path to the distribution folder created by build-standalone.ps1. Default: .\dist

.PARAMETER AppVersion
    Version number for the installer. Default: 1.0.0

.PARAMETER CompanyName
    Company name for the installer metadata. Default: Your Company

.PARAMETER NSISPath
    Path to NSIS makensis.exe. If not provided, will search common locations.

.EXAMPLE
    .\build-installer.ps1

.EXAMPLE
    .\build-installer.ps1 -AppVersion "2.1.0" -CompanyName "Acme Corp"

.EXAMPLE
    .\build-installer.ps1 -OutputPath "C:\Installers" -NSISPath "C:\Program Files (x86)\NSIS\makensis.exe"
#>

param(
    [string]$OutputPath = ".\installer",
    [string]$DistPath = ".\dist",
    [string]$AppVersion = "1.0.0",
    [string]$CompanyName = "Your Company",
    [string]$NSISPath = $null
)

$ErrorActionPreference = "Stop"

# Configuration
$AppName = "MSMQ Manager"
$AppDisplayName = "MSMQ Manager & Monitor"
$ServiceName = "MSMQMonitor"
$AppExe = "MsMqApp.exe"
$AppDescription = "Web-based MSMQ Manager and Monitor Tool"
$AppWebsite = "https://github.com/m-silliman/msmq-web"
$DefaultPort = "9090"

# Get script directory
$scriptPath = Split-Path -Parent $MyInvocation.MyCommand.Path

# Handle relative and absolute paths correctly
if ([System.IO.Path]::IsPathRooted($DistPath)) {
    $distFullPath = $DistPath
} else {
    $distFullPath = Join-Path $scriptPath $DistPath
}

if ([System.IO.Path]::IsPathRooted($OutputPath)) {
    $outputFullPath = $OutputPath
} else {
    $outputFullPath = Join-Path $scriptPath $OutputPath
}

Write-Host "========================================" -ForegroundColor Cyan
Write-Host "MSMQ Manager - Installer Builder" -ForegroundColor Cyan
Write-Host "========================================" -ForegroundColor Cyan
Write-Host ""

# Validate distribution folder exists
if (-not (Test-Path $distFullPath)) {
    Write-Host "ERROR: Distribution folder not found at: $distFullPath" -ForegroundColor Red
    Write-Host "Please run build-standalone.ps1 first to create the distribution." -ForegroundColor Yellow
    exit 1
}

# Check for main executable
$exePath = Join-Path $distFullPath $AppExe
if (-not (Test-Path $exePath)) {
    Write-Host "ERROR: Application executable not found at: $exePath" -ForegroundColor Red
    exit 1
}

# Find NSIS installation
if (-not $NSISPath) {
    $possiblePaths = @(
        "${env:ProgramFiles(x86)}\NSIS\makensis.exe",
        "${env:ProgramFiles}\NSIS\makensis.exe",
        "C:\Program Files (x86)\NSIS\makensis.exe",
        "C:\Program Files\NSIS\makensis.exe"
    )
    
    foreach ($path in $possiblePaths) {
        if (Test-Path $path) {
            $NSISPath = $path
            break
        }
    }
}

if (-not $NSISPath -or -not (Test-Path $NSISPath)) {
    Write-Host "ERROR: NSIS not found. Please install NSIS from https://nsis.sourceforge.io/" -ForegroundColor Red
    Write-Host "Or specify the path using -NSISPath parameter." -ForegroundColor Yellow
    exit 1
}

Write-Host "Build Settings:" -ForegroundColor Green
Write-Host "  App Name:      $AppDisplayName" -ForegroundColor White
Write-Host "  Version:       $AppVersion" -ForegroundColor White
Write-Host "  Company:       $CompanyName" -ForegroundColor White
Write-Host "  Service Name:  $ServiceName" -ForegroundColor White
Write-Host "  Distribution:  $distFullPath" -ForegroundColor White
Write-Host "  Output:        $outputFullPath" -ForegroundColor White
Write-Host "  NSIS:          $NSISPath" -ForegroundColor White
Write-Host ""

# Create output directory
if (Test-Path $outputFullPath) {
    Remove-Item $outputFullPath -Recurse -Force
}
New-Item -ItemType Directory -Path $outputFullPath -Force | Out-Null

# Generate version information for NSIS
$versionParts = $AppVersion -split '\.'
while ($versionParts.Count -lt 4) {
    $versionParts += "0"
}
$nsisVersion = $versionParts[0..3] -join '.'
$displayVersion = $versionParts[0..2] -join '.'

# Get current date for installer
$buildDate = Get-Date -Format "yyyy-MM-dd"

Write-Host "Generating NSIS installer script..." -ForegroundColor Green

# Create the NSIS script
$nsisScript = @"
;NSIS Installer Script for $AppDisplayName
;Generated by build-installer.ps1 on $(Get-Date -Format "yyyy-MM-dd HH:mm:ss")

;--------------------------------
;Include Modern UI

!include "MUI2.nsh"
!include "x64.nsh"
!include "LogicLib.nsh"

;--------------------------------
;General

;Name and file
Name "$AppDisplayName"
OutFile "$outputFullPath\${AppName}Setup-v${displayVersion}.exe"

;Default installation folder
InstallDir "`$PROGRAMFILES64\$AppName"

;Get installation folder from registry if available
InstallDirRegKey HKCU "Software\$CompanyName\$AppName" ""

;Request application privileges for Windows Vista/7/8/10/11
RequestExecutionLevel admin

;Show install details
ShowInstDetails show
ShowUnInstDetails show

;--------------------------------
;Version Information

VIProductVersion "$nsisVersion"
VIAddVersionKey "ProductName" "$AppDisplayName"
VIAddVersionKey "Comments" "$AppDescription"
VIAddVersionKey "CompanyName" "$CompanyName"
VIAddVersionKey "LegalCopyright" "Copyright © $(Get-Date -Format yyyy) $CompanyName"
VIAddVersionKey "FileDescription" "$AppDisplayName Installer"
VIAddVersionKey "FileVersion" "$AppVersion"
VIAddVersionKey "ProductVersion" "$AppVersion"
VIAddVersionKey "InternalName" "$AppName"

;--------------------------------
;Interface Settings

!define MUI_ABORTWARNING
!define MUI_ICON "`${NSISDIR}\Contrib\Graphics\Icons\modern-install.ico"
!define MUI_UNICON "`${NSISDIR}\Contrib\Graphics\Icons\modern-uninstall.ico"

;--------------------------------
;Pages

!insertmacro MUI_PAGE_LICENSE "license.txt"
!insertmacro MUI_PAGE_COMPONENTS
!insertmacro MUI_PAGE_DIRECTORY

;Custom page for service configuration
Page custom ServiceConfigPage ServiceConfigPageLeave

!insertmacro MUI_PAGE_INSTFILES
!insertmacro MUI_PAGE_FINISH

!insertmacro MUI_UNPAGE_CONFIRM
!insertmacro MUI_UNPAGE_INSTFILES

;--------------------------------
;Languages

!insertmacro MUI_LANGUAGE "English"

;--------------------------------
;Variables

Var /GLOBAL InstallAsService
Var /GLOBAL StartService
Var /GLOBAL ServicePort
Var /GLOBAL CreateDesktopShortcut
Var /GLOBAL CreateStartMenuShortcut

;--------------------------------
;Installer Sections

Section "Core Application" SecCore
  SectionIn RO
  
  SetOutPath "`$INSTDIR"
  
  ;Stop service if it exists
  ExecWait 'sc stop "$ServiceName"' `$0
  ExecWait 'sc delete "$ServiceName"' `$0
  
  ;Install all files
  File /r "$distFullPath\*.*"
  
  ;Store installation folder
  WriteRegStr HKCU "Software\$CompanyName\$AppName" "" `$INSTDIR
  
  ;Create uninstaller
  WriteUninstaller "`$INSTDIR\uninstall.exe"
  
  ;Add to Add/Remove Programs
  WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\$AppName" "DisplayName" "$AppDisplayName"
  WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\$AppName" "DisplayVersion" "$displayVersion"
  WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\$AppName" "Publisher" "$CompanyName"
  WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\$AppName" "UninstallString" "`$INSTDIR\uninstall.exe"
  WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\$AppName" "InstallLocation" "`$INSTDIR"
  WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\$AppName" "DisplayIcon" "`$INSTDIR\$AppExe"
  WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\$AppName" "HelpLink" "$AppWebsite"
  WriteRegDWORD HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\$AppName" "NoModify" 1
  WriteRegDWORD HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\$AppName" "NoRepair" 1
  
  ;Write estimated size (approximate)
  WriteRegDWORD HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\$AppName" "EstimatedSize" "102400"  ; ~100MB

SectionEnd

Section "Windows Service" SecService
  
  ;Copy PowerShell script for port configuration
  File "update-port.ps1"
  
  ;Execute PowerShell script to update configuration
  ExecWait 'powershell.exe -ExecutionPolicy Bypass -File "`$INSTDIR\update-port.ps1" -InstallDir "`$INSTDIR" -Port `$ServicePort' `$0
  
  ;Clean up temporary script
  Delete "`$INSTDIR\update-port.ps1"
  
  ;Install Windows service using sc command
  ExecWait 'sc create "$ServiceName" binPath= "`$INSTDIR\$AppExe" start= auto DisplayName= "$AppDisplayName"' `$0
  ExecWait 'sc description "$ServiceName" "$AppDescription"' `$0
  
  ;Start service if requested
  `${If} `$StartService == "1"
    ExecWait 'sc start "$ServiceName"' `$0
  `${EndIf}
  
  ;Add firewall rule for the port
  ExecWait 'netsh advfirewall firewall delete rule name="$AppDisplayName"'
  ExecWait 'netsh advfirewall firewall add rule name="$AppDisplayName" dir=in action=allow protocol=TCP localport=`$ServicePort'
  
SectionEnd

Section "Desktop Shortcut" SecDesktop
  CreateShortCut "`$DESKTOP\$AppDisplayName.lnk" "http://localhost:`$ServicePort" "" "`$INSTDIR\$AppExe" 0
SectionEnd

Section "Start Menu Shortcuts" SecStartMenu
  CreateDirectory "`$SMPROGRAMS\$AppName"
  CreateShortCut "`$SMPROGRAMS\$AppName\$AppDisplayName.lnk" "http://localhost:`$ServicePort" "" "`$INSTDIR\$AppExe" 0
  CreateShortCut "`$SMPROGRAMS\$AppName\Uninstall.lnk" "`$INSTDIR\uninstall.exe"
  CreateShortCut "`$SMPROGRAMS\$AppName\Application Folder.lnk" "`$INSTDIR"
SectionEnd

;--------------------------------
;Section Descriptions

!insertmacro MUI_FUNCTION_DESCRIPTION_BEGIN
!insertmacro MUI_DESCRIPTION_TEXT `${SecCore} "Core application files (required)"
!insertmacro MUI_DESCRIPTION_TEXT `${SecService} "Install and configure as Windows Service (recommended)"
!insertmacro MUI_DESCRIPTION_TEXT `${SecDesktop} "Create desktop shortcut to web interface"
!insertmacro MUI_DESCRIPTION_TEXT `${SecStartMenu} "Create Start Menu shortcuts"
!insertmacro MUI_FUNCTION_DESCRIPTION_END

;--------------------------------
;Custom Service Configuration Page

Function ServiceConfigPage
  !insertmacro MUI_HEADER_TEXT "Service Configuration" "Configure Windows Service settings"
  
  nsDialogs::Create 1018
  Pop `$0
  
  `${NSD_CreateLabel} 0 0 100% 20u "Configure how $AppDisplayName should run as a Windows Service:"
  
  `${NSD_CreateCheckBox} 0 30u 100% 15u "&Install as Windows Service (recommended)"
  Pop `$1
  `${NSD_SetState} `$1 `${BST_CHECKED}
  
  `${NSD_CreateCheckBox} 20u 50u 100% 15u "&Start service automatically after installation"
  Pop `$2
  `${NSD_SetState} `$2 `${BST_CHECKED}
  
  `${NSD_CreateLabel} 0 75u 100u 15u "Web Interface Port:"
  `${NSD_CreateNumber} 0 90u 80u 15u "$DefaultPort"
  Pop `$3
  
  `${NSD_CreateLabel} 0 115u 100% 15u "The web interface will be available at: http://localhost:[port]"
  
  `${NSD_CreateCheckBox} 0 140u 100% 15u "Create &Desktop shortcut to web interface"
  Pop `$4
  `${NSD_SetState} `$4 `${BST_CHECKED}
  
  `${NSD_CreateCheckBox} 0 160u 100% 15u "Create &Start Menu shortcuts"
  Pop `$5
  `${NSD_SetState} `$5 `${BST_CHECKED}
  
  ; Store control handles
  StrCpy `$InstallAsService `$1
  StrCpy `$StartService `$2
  StrCpy `$ServicePort `$3
  StrCpy `$CreateDesktopShortcut `$4
  StrCpy `$CreateStartMenuShortcut `$5
  
  nsDialogs::Show
FunctionEnd

Function ServiceConfigPageLeave
  ; Get checkbox states
  `${NSD_GetState} `$InstallAsService `$0
  `${If} `$0 == `${BST_CHECKED}
    StrCpy `$InstallAsService "1"
    !insertmacro SelectSection `${SecService}
  `${Else}
    StrCpy `$InstallAsService "0"
    !insertmacro UnselectSection `${SecService}
  `${EndIf}
  
  `${NSD_GetState} `$StartService `$0
  `${If} `$0 == `${BST_CHECKED}
    StrCpy `$StartService "1"
  `${Else}
    StrCpy `$StartService "0"
  `${EndIf}
  
  `${NSD_GetText} `$ServicePort `$ServicePort
  
  `${NSD_GetState} `$CreateDesktopShortcut `$0
  `${If} `$0 == `${BST_CHECKED}
    StrCpy `$CreateDesktopShortcut "1"
    !insertmacro SelectSection `${SecDesktop}
  `${Else}
    StrCpy `$CreateDesktopShortcut "0"
    !insertmacro UnselectSection `${SecDesktop}
  `${EndIf}
  
  `${NSD_GetState} `$CreateStartMenuShortcut `$0
  `${If} `$0 == `${BST_CHECKED}
    StrCpy `$CreateStartMenuShortcut "1"
    !insertmacro SelectSection `${SecStartMenu}
  `${Else}
    StrCpy `$CreateStartMenuShortcut "0"
    !insertmacro UnselectSection `${SecStartMenu}
  `${EndIf}
FunctionEnd

;--------------------------------
;Helper Functions



;--------------------------------
;Initialization

Function .onInit
  ; Check if we're on 64-bit Windows
  `${IfNot} `${RunningX64}
    MessageBox MB_OK|MB_ICONSTOP "This application requires 64-bit Windows."
    Abort
  `${EndIf}
  
  ; Check for admin privileges
  UserInfo::GetAccountType
  Pop `$0
  `${If} `$0 != "admin"
    MessageBox MB_OK|MB_ICONSTOP "Administrator privileges are required to install this application."
    Abort
  `${EndIf}
  
  ; Initialize variables with defaults
  StrCpy `$InstallAsService "1"
  StrCpy `$StartService "1"
  StrCpy `$ServicePort "$DefaultPort"
  StrCpy `$CreateDesktopShortcut "1"
  StrCpy `$CreateStartMenuShortcut "1"
  

FunctionEnd

;--------------------------------
;Uninstaller Section

Section "Uninstall"
  
  ; Stop and remove service
  ExecWait 'sc stop "$ServiceName"' `$0
  ExecWait 'sc delete "$ServiceName"' `$0
  
  ; Remove firewall rule
  ExecWait 'netsh advfirewall firewall delete rule name="$AppDisplayName"'
  
  ; Remove files and directories
  RMDir /r "`$INSTDIR"
  
  ; Remove registry keys
  DeleteRegKey HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\$AppName"
  DeleteRegKey HKCU "Software\$CompanyName\$AppName"
  
  ; Remove shortcuts
  Delete "`$DESKTOP\$AppDisplayName.lnk"
  RMDir /r "`$SMPROGRAMS\$AppName"

SectionEnd
"@

# Create license file first
$licenseContent = @"
MIT License

MSMQ Manager & Monitor

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
"@

$licensePath = Join-Path $outputFullPath "license.txt"
Set-Content -Path $licensePath -Value $licenseContent -Encoding UTF8

# Create PowerShell script for port configuration
$portUpdateScript = @'
param([string]$InstallDir, [int]$Port)

$configPath = Join-Path $InstallDir 'appsettings.json'
if (Test-Path $configPath) {
    try {
        $config = Get-Content $configPath | ConvertFrom-Json
        $config.Service.Port = $Port
        $config | ConvertTo-Json -Depth 10 | Set-Content $configPath
        Write-Host "Updated port configuration to $Port"
    } catch {
        Write-Host "Error updating configuration: $_"
    }
} else {
    Write-Host "Configuration file not found: $configPath"
}
'@

$portScriptPath = Join-Path $outputFullPath "update-port.ps1"
Set-Content -Path $portScriptPath -Value $portUpdateScript -Encoding UTF8

# Write the NSIS script
$nsisScriptPath = Join-Path $outputFullPath "installer.nsi"
Set-Content -Path $nsisScriptPath -Value $nsisScript -Encoding UTF8

Write-Host "Generated NSIS script: $nsisScriptPath" -ForegroundColor Gray

# Check NSIS is ready
Write-Host "NSIS installation validated." -ForegroundColor Green

# Build the installer
Write-Host "Building installer with NSIS..." -ForegroundColor Green
Write-Host ""

try {
    $process = Start-Process -FilePath $NSISPath -ArgumentList "`"$nsisScriptPath`"" -Wait -PassThru -NoNewWindow
    
    if ($process.ExitCode -ne 0) {
        throw "NSIS compilation failed with exit code $($process.ExitCode)"
    }
}
catch {
    Write-Host ""
    Write-Host "ERROR: Installer build failed: $_" -ForegroundColor Red
    Write-Host ""
    Write-Host "Common issues and solutions:" -ForegroundColor Yellow
    Write-Host "1. Missing ServiceLib plugin - download from https://nsis.sourceforge.io/ServiceLib_plug-in" -ForegroundColor Gray
    Write-Host "2. NSIS version compatibility - try NSIS 3.08 or later" -ForegroundColor Gray
    Write-Host "3. Path issues - ensure no spaces in paths or use quotes" -ForegroundColor Gray
    exit 1
}

# Find the created installer
$installerPattern = Join-Path $outputFullPath "*.exe"
$installerFile = Get-ChildItem $installerPattern | Select-Object -First 1

if ($installerFile) {
    $installerSize = [math]::Round($installerFile.Length / 1MB, 2)
    
    Write-Host ""
    Write-Host "========================================" -ForegroundColor Green
    Write-Host "Installer Build Complete!" -ForegroundColor Green
    Write-Host "========================================" -ForegroundColor Green
    Write-Host ""
    Write-Host "Installer Details:" -ForegroundColor Cyan
    Write-Host "  File: $($installerFile.Name)" -ForegroundColor White
    Write-Host "  Size: $installerSize MB" -ForegroundColor White
    Write-Host "  Location: $($installerFile.FullName)" -ForegroundColor White
    Write-Host "  Version: $displayVersion" -ForegroundColor White
    Write-Host ""
    Write-Host "Installer Features:" -ForegroundColor Cyan
    Write-Host "  ✓ User-selectable installation path" -ForegroundColor Green
    Write-Host "  ✓ Automatic Windows Service registration" -ForegroundColor Green
    Write-Host "  ✓ Configurable web interface port" -ForegroundColor Green
    Write-Host "  ✓ Automatic firewall rule creation" -ForegroundColor Green
    Write-Host "  ✓ Desktop and Start Menu shortcuts" -ForegroundColor Green
    Write-Host "  ✓ Standard Add/Remove Programs integration" -ForegroundColor Green
    Write-Host "  ✓ Clean uninstaller with service removal" -ForegroundColor Green
    Write-Host ""
    Write-Host "Usage:" -ForegroundColor Cyan
    Write-Host "  Run the installer as Administrator to install $AppDisplayName" -ForegroundColor Yellow
    Write-Host "  The installer will guide you through service configuration" -ForegroundColor Yellow
    Write-Host "  Default web interface: http://localhost:9090" -ForegroundColor Yellow
    Write-Host ""
    
    # NSIS script already exists in output directory for reference
    Write-Host "NSIS script saved as: installer.nsi" -ForegroundColor Gray
}
else {
    Write-Host ""
    Write-Host "WARNING: Installer executable not found in output directory" -ForegroundColor Yellow
    Write-Host "Check the NSIS compilation output above for errors" -ForegroundColor Yellow
}

Write-Host ""